version: '3'

services:
    ChaldeaDb:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: Utilisateurs
        ports:
            - "3306:3306"
    
    
    site_service:
        build:
            context: ./site_service
            dockerfile: dockerfile
        environment:
            FLASK_ENV: development
            FLASK_APP: site.py

        ports:
            - '5000:5000'